language: node_js
node_js:
  - 6.4.0
services:
  - couchdb
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
